apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: StackitCluster
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-stackit
    app.kubernetes.io/managed-by: kustomize
  name: stackitcluster-sample
spec:
  projectID: 00000000-0000-0000-0000-000000000000
  region: eu01
  credentialsSecretRef:
    name: stackit-credentials
  network:
    id: 11111111-1111-1111-1111-111111111111
  apiServerLoadBalancer:
    enabled: true
