## Append samples of your project ##
resources:
- infrastructure_v1alpha1_stackitcluster.yaml
- infrastructure_v1alpha1_stackitmachine.yaml
- infrastructure_v1alpha1_stackitclustertemplate.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
