//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/cluster-api/api/core/v1beta2"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackitAPIServerLoadBalancerSpec) DeepCopyInto(out *StackitAPIServerLoadBalancerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackitAPIServerLoadBalancerSpec.
func (in *StackitAPIServerLoadBalancerSpec) DeepCopy() *StackitAPIServerLoadBalancerSpec {
	if in == nil {
		return nil
	}
	out := new(StackitAPIServerLoadBalancerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackitBastionCloudInitRef) DeepCopyInto(out *StackitBastionCloudInitRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackitBastionCloudInitRef.
func (in *StackitBastionCloudInitRef) DeepCopy() *StackitBastionCloudInitRef {
	if in == nil {
		return nil
	}
	out := new(StackitBastionCloudInitRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackitBastionSpec) DeepCopyInto(out *StackitBastionSpec) {
	*out = *in
	if in.AllowedCIDRs != nil {
		in, out := &in.AllowedCIDRs, &out.AllowedCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.RootVolume.DeepCopyInto(&out.RootVolume)
	if in.CloudInitRef != nil {
		in, out := &in.CloudInitRef, &out.CloudInitRef
		*out = new(StackitBastionCloudInitRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackitBastionSpec.
func (in *StackitBastionSpec) DeepCopy() *StackitBastionSpec {
	if in == nil {
		return nil
	}
	out := new(StackitBastionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackitBastionStatus) DeepCopyInto(out *StackitBastionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackitBastionStatus.
func (in *StackitBastionStatus) DeepCopy() *StackitBastionStatus {
	if in == nil {
		return nil
	}
	out := new(StackitBastionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackitCluster) DeepCopyInto(out *StackitCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackitCluster.
func (in *StackitCluster) DeepCopy() *StackitCluster {
	if in == nil {
		return nil
	}
	out := new(StackitCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StackitCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackitClusterInitializationStatus) DeepCopyInto(out *StackitClusterInitializationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackitClusterInitializationStatus.
func (in *StackitClusterInitializationStatus) DeepCopy() *StackitClusterInitializationStatus {
	if in == nil {
		return nil
	}
	out := new(StackitClusterInitializationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackitClusterList) DeepCopyInto(out *StackitClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StackitCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackitClusterList.
func (in *StackitClusterList) DeepCopy() *StackitClusterList {
	if in == nil {
		return nil
	}
	out := new(StackitClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StackitClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackitClusterNetworkSpec) DeepCopyInto(out *StackitClusterNetworkSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackitClusterNetworkSpec.
func (in *StackitClusterNetworkSpec) DeepCopy() *StackitClusterNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(StackitClusterNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackitClusterSpec) DeepCopyInto(out *StackitClusterSpec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
	out.Network = in.Network
	out.APIServerLoadBalancer = in.APIServerLoadBalancer
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	in.Bastion.DeepCopyInto(&out.Bastion)
	if in.AdditionalLabels != nil {
		in, out := &in.AdditionalLabels, &out.AdditionalLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackitClusterSpec.
func (in *StackitClusterSpec) DeepCopy() *StackitClusterSpec {
	if in == nil {
		return nil
	}
	out := new(StackitClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackitClusterStatus) DeepCopyInto(out *StackitClusterStatus) {
	*out = *in
	out.Initialization = in.Initialization
	out.APIServerEndpoint = in.APIServerEndpoint
	out.Bastion = in.Bastion
	if in.FailureDomains != nil {
		in, out := &in.FailureDomains, &out.FailureDomains
		*out = make([]v1beta2.FailureDomain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackitClusterStatus.
func (in *StackitClusterStatus) DeepCopy() *StackitClusterStatus {
	if in == nil {
		return nil
	}
	out := new(StackitClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackitClusterTemplate) DeepCopyInto(out *StackitClusterTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackitClusterTemplate.
func (in *StackitClusterTemplate) DeepCopy() *StackitClusterTemplate {
	if in == nil {
		return nil
	}
	out := new(StackitClusterTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StackitClusterTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackitClusterTemplateList) DeepCopyInto(out *StackitClusterTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StackitClusterTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackitClusterTemplateList.
func (in *StackitClusterTemplateList) DeepCopy() *StackitClusterTemplateList {
	if in == nil {
		return nil
	}
	out := new(StackitClusterTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StackitClusterTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackitClusterTemplateResource) DeepCopyInto(out *StackitClusterTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackitClusterTemplateResource.
func (in *StackitClusterTemplateResource) DeepCopy() *StackitClusterTemplateResource {
	if in == nil {
		return nil
	}
	out := new(StackitClusterTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackitClusterTemplateSpec) DeepCopyInto(out *StackitClusterTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackitClusterTemplateSpec.
func (in *StackitClusterTemplateSpec) DeepCopy() *StackitClusterTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(StackitClusterTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackitMachine) DeepCopyInto(out *StackitMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackitMachine.
func (in *StackitMachine) DeepCopy() *StackitMachine {
	if in == nil {
		return nil
	}
	out := new(StackitMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StackitMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackitMachineInitializationStatus) DeepCopyInto(out *StackitMachineInitializationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackitMachineInitializationStatus.
func (in *StackitMachineInitializationStatus) DeepCopy() *StackitMachineInitializationStatus {
	if in == nil {
		return nil
	}
	out := new(StackitMachineInitializationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackitMachineList) DeepCopyInto(out *StackitMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StackitMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackitMachineList.
func (in *StackitMachineList) DeepCopy() *StackitMachineList {
	if in == nil {
		return nil
	}
	out := new(StackitMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StackitMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackitMachineNetworkSpec) DeepCopyInto(out *StackitMachineNetworkSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackitMachineNetworkSpec.
func (in *StackitMachineNetworkSpec) DeepCopy() *StackitMachineNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(StackitMachineNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackitMachineSpec) DeepCopyInto(out *StackitMachineSpec) {
	*out = *in
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(string)
		**out = **in
	}
	in.RootVolume.DeepCopyInto(&out.RootVolume)
	out.Network = in.Network
	if in.SecurityGroups != nil {
		in, out := &in.SecurityGroups, &out.SecurityGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdditionalLabels != nil {
		in, out := &in.AdditionalLabels, &out.AdditionalLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackitMachineSpec.
func (in *StackitMachineSpec) DeepCopy() *StackitMachineSpec {
	if in == nil {
		return nil
	}
	out := new(StackitMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackitMachineStatus) DeepCopyInto(out *StackitMachineStatus) {
	*out = *in
	out.Initialization = in.Initialization
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]v1beta2.MachineAddress, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackitMachineStatus.
func (in *StackitMachineStatus) DeepCopy() *StackitMachineStatus {
	if in == nil {
		return nil
	}
	out := new(StackitMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackitMachineTemplate) DeepCopyInto(out *StackitMachineTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackitMachineTemplate.
func (in *StackitMachineTemplate) DeepCopy() *StackitMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(StackitMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StackitMachineTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackitMachineTemplateList) DeepCopyInto(out *StackitMachineTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StackitMachineTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackitMachineTemplateList.
func (in *StackitMachineTemplateList) DeepCopy() *StackitMachineTemplateList {
	if in == nil {
		return nil
	}
	out := new(StackitMachineTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StackitMachineTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackitMachineTemplateResource) DeepCopyInto(out *StackitMachineTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackitMachineTemplateResource.
func (in *StackitMachineTemplateResource) DeepCopy() *StackitMachineTemplateResource {
	if in == nil {
		return nil
	}
	out := new(StackitMachineTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackitMachineTemplateSpec) DeepCopyInto(out *StackitMachineTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackitMachineTemplateSpec.
func (in *StackitMachineTemplateSpec) DeepCopy() *StackitMachineTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(StackitMachineTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackitRootVolumeSpec) DeepCopyInto(out *StackitRootVolumeSpec) {
	*out = *in
	if in.DeleteOnTermination != nil {
		in, out := &in.DeleteOnTermination, &out.DeleteOnTermination
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackitRootVolumeSpec.
func (in *StackitRootVolumeSpec) DeepCopy() *StackitRootVolumeSpec {
	if in == nil {
		return nil
	}
	out := new(StackitRootVolumeSpec)
	in.DeepCopyInto(out)
	return out
}
