apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: ${NAMESPACE}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16
    services:
      cidrBlocks:
        - 10.128.0.0/12
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: StackitCluster
    name: ${CLUSTER_NAME}
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: KubeadmControlPlane
    name: ${CLUSTER_NAME}-control-plane
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: StackitCluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: ${NAMESPACE}
spec:
  projectID: ${STACKIT_PROJECT_ID}
  region: ${STACKIT_REGION}
  credentialsSecretRef:
    name: ${STACKIT_CREDENTIALS_SECRET_NAME}
    namespace: ${NAMESPACE}
  network:
    id: ${STACKIT_NETWORK_ID}
  apiServerLoadBalancer:
    enabled: true
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KubeadmControlPlane
metadata:
  name: ${CLUSTER_NAME}-control-plane
  namespace: ${NAMESPACE}
spec:
  replicas: ${CONTROL_PLANE_MACHINE_COUNT}
  version: ${KUBERNETES_VERSION}
  machineTemplate:
    spec:
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: StackitMachineTemplate
        name: ${CLUSTER_NAME}-control-plane
  kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        name: '{{ ds.meta_data.local_hostname }}'
        criSocket: unix:///var/run/containerd/containerd.sock
        kubeletExtraArgs:
          - name: cloud-provider
            value: external
    joinConfiguration:
      nodeRegistration:
        name: '{{ ds.meta_data.local_hostname }}'
        criSocket: unix:///var/run/containerd/containerd.sock
        kubeletExtraArgs:
          - name: cloud-provider
            value: external
    clusterConfiguration:
      apiServer:
        extraArgs:
          - name: cloud-provider
            value: external
      controllerManager:
        extraArgs:
          - name: cloud-provider
            value: external
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: StackitMachineTemplate
metadata:
  name: ${CLUSTER_NAME}-control-plane
  namespace: ${NAMESPACE}
spec:
  template:
    spec:
      imageID: ${STACKIT_IMAGE_ID}
      machineType: ${STACKIT_MACHINE_TYPE}
      sshKeyName: ${STACKIT_SSH_KEY_NAME}
      rootVolume:
        sizeGiB: 50
        performanceClass: storage_premium_perf6
        deleteOnTermination: true
      network:
        id: ${STACKIT_NETWORK_ID}
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  name: ${CLUSTER_NAME}-md-0
  namespace: ${NAMESPACE}
spec:
  clusterName: ${CLUSTER_NAME}
  replicas: ${WORKER_MACHINE_COUNT}
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
      cluster.x-k8s.io/deployment-name: ${CLUSTER_NAME}-md-0
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
        cluster.x-k8s.io/deployment-name: ${CLUSTER_NAME}-md-0
    spec:
      clusterName: ${CLUSTER_NAME}
      version: ${KUBERNETES_VERSION}
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: KubeadmConfigTemplate
          name: ${CLUSTER_NAME}-md-0
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: StackitMachineTemplate
        name: ${CLUSTER_NAME}-md-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: StackitMachineTemplate
metadata:
  name: ${CLUSTER_NAME}-md-0
  namespace: ${NAMESPACE}
spec:
  template:
    spec:
      imageID: ${STACKIT_IMAGE_ID}
      machineType: ${STACKIT_MACHINE_TYPE}
      sshKeyName: ${STACKIT_SSH_KEY_NAME}
      rootVolume:
        sizeGiB: 50
        performanceClass: storage_premium_perf6
        deleteOnTermination: true
      network:
        id: ${STACKIT_NETWORK_ID}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: KubeadmConfigTemplate
metadata:
  name: ${CLUSTER_NAME}-md-0
  namespace: ${NAMESPACE}
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          name: '{{ ds.meta_data.local_hostname }}'
          criSocket: unix:///var/run/containerd/containerd.sock
          kubeletExtraArgs:
            - name: cloud-provider
              value: external
